server:
  port: 8086
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.103:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.0.103:8082/realms/selmag
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: 4bHWLTJq8emL3kTuUeoQaQJxWrK5SfkR
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: 4bHWLTJq8emL3kTuUeoQaQJxWrK5SfkR
          discovery:
            provider: keycloak
            client-id: admin-service
            client-secret: 4bHWLTJq8emL3kTuUeoQaQJxWrK5SfkR
            authorization-grant-type: client_credentials
            scope:
              - discovery
  application:
    name: selmag-admin-service
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  client:
    service-url:
      service-url:
        defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true