server:
  port: 8086
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: NoclP60cPMbyeFKH3tAFGIC51i0M3Xt0
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: NoclP60cPMbyeFKH3tAFGIC51i0M3Xt0
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus