selmag:
  services:
    catalogue:
      registration-id: keycloak
      uri: http://localhost:8081
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: manager-app
            client-secret: ha1tnrrxOH0OVgkD1UCrgrsv6hGIyPzg
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
        provider:
          keycloak:
            issuer-uri: http://192.168.0.103:8082/realms/selmag
            user-name-attribute: preferred_username