server:
  port: 8888
spring:
  application:
    name: selmag-config-service
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/GlazyrinAV/salmag-parent-s24.git
          default-label: main
          search-paths:
            - 'config/cloud/{application}/{profile}'