server:
  port: 8888
spring:
  application:
    name: selmag-config-service
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/dev/salmag-parent-s24/config/cloud
