selmag:
  service:
    catalogue:
      uri: lb://selmag-catalogue-service
    feedback:
      uri: lb://selmag-feedback-service
server:
  port: 8083
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: zFKs1HSCAg4jPO9Lz36WMquRto2MkVw2
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalogue
          discovery:
            provider: keycloak
            client-id: customer-app
            client-secret: zFKs1HSCAg4jPO9Lz36WMquRto2MkVw2
            authorization-grant-type: client_credentials
            scope:
              - discovery
  boot:
    admin:
      client:
        enabled: false
  application:
    name: selmag-customer-app
eureka:
  client:
    service-url:
      service-url:
        defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'