selmag:
  service:
    catalogue:
      uri: http://localhost:8081
    feedback:
      uri: http://localhost:8084

server:
  port: 8083
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.0.103:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: hUSE7JBtlE3LhUrIhEnAaYVXNELFD7Mn
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalogue
  application:
    name: selmag-customer-app